# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 06:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold', models.IntegerField(default=0, verbose_name='\u91d1\u5e01')),
                ('balance', models.IntegerField(default=0, verbose_name='\u4f59\u989d(\u5206)')),
                ('cashed_balance', models.IntegerField(default=0, verbose_name='\u5df2\u63d0\u73b0\u91d1\u989d(\u5206)')),
                ('total_get', models.IntegerField(default=0, verbose_name='\u7d2f\u8ba1\u6536\u5165(\u5206)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
        ),
    ]
