# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 11:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldToMoneyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold', models.IntegerField(default=0, verbose_name='\u91d1\u5e01')),
                ('balance', models.IntegerField(default=0, verbose_name='\u4eba\u6c11\u5e01(\u5206)')),
                ('exchange_rate', models.TextField(default='', verbose_name='\u5151\u7387\u4fe1\u606f')),
                ('first_created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa')),
                ('last_modify', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='\u65e5\u671f'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_modify',
            field=models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4'),
        ),
    ]
