# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 14:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_auto_20171128_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetGoldRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold', models.IntegerField(default=0, verbose_name='\u83b7\u53d6\u91d1\u5e01')),
                ('first_created', models.DateTimeField(auto_now_add=True, verbose_name='\u65e5\u671f')),
                ('last_modify', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u91d1\u5e01\u83b7\u53d6\u8bb0\u5f55',
                'verbose_name_plural': '\u91d1\u5e01\u83b7\u53d6\u8bb0\u5f55',
            },
        ),
        migrations.AddIndex(
            model_name='getgoldrecord',
            index=models.Index(fields=['user', 'first_created'], name='account_get_user_id_63707f_idx'),
        ),
    ]
