# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20171128_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='getgoldrecord',
            name='exchanged',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u5df2\u8f6c\u6362'),
        ),
    ]
