# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_getgoldrecord_exchanged'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goldtomoneyrecord',
            options={'verbose_name': '\u91d1\u5e01\u8f6c\u6362\u8bb0\u5f55', 'verbose_name_plural': '\u91d1\u5e01\u8f6c\u6362\u8bb0\u5f55'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '\u7528\u6237\u91d1\u5e01', 'verbose_name_plural': '\u7528\u6237\u91d1\u5e01'},
        ),
    ]
