# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 13:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0009_auto_20171204_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='\u95ee\u9898\u63cf\u8ff0')),
                ('pictures', models.TextField(verbose_name='\u56fe\u7247')),
                ('contact', models.TextField(verbose_name='\u8054\u7cfb\u65b9\u5f0f')),
                ('phone', models.CharField(max_length=50, verbose_name='\u624b\u673a\u53f7')),
                ('first_created', models.DateTimeField(auto_now_add=True, verbose_name='\u65e5\u671f')),
                ('last_modify', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u53cd\u9988',
                'verbose_name_plural': '\u7528\u6237\u53cd\u9988',
            },
        ),
    ]
