# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-08 13:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_userfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback',
            name='User',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237'),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='contact',
            field=models.TextField(default='', verbose_name='\u8054\u7cfb\u65b9\u5f0f'),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='description',
            field=models.TextField(default='', verbose_name='\u95ee\u9898\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='phone',
            field=models.CharField(default='', max_length=50, verbose_name='\u624b\u673a\u53f7'),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='pictures',
            field=models.TextField(default='', verbose_name='\u56fe\u7247'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='balance',
            field=models.FloatField(default=0, verbose_name='\u4f59\u989d(\u5206)'),
        ),
    ]
