# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-08 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20171208_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cashed_balance',
            field=models.FloatField(default=0, verbose_name='\u5df2\u63d0\u73b0\u91d1\u989d(\u5206)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='total_get',
            field=models.FloatField(default=0, verbose_name='\u7d2f\u8ba1\u6536\u5165(\u5206)'),
        ),
    ]
