# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-14 02:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20171208_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfeedback',
            name='User',
        ),
    ]
