# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 14:07
from __future__ import unicode_literals

from django.db import migrations, models

from ad.models import REWARD_CONDITION_CHOICE


def forwards_func(apps, schema_editor):
    RewardCondition = apps.get_model("ad", "RewardCondition")
    RewardCondition.objects.create(typ=REWARD_CONDITION_CHOICE[0][1], )
    RewardCondition.objects.create(typ=REWARD_CONDITION_CHOICE[1][1], )

    GlobalShieldConfig = apps.get_model("ad", "GlobalShieldConfig")
    GlobalShieldConfig.objects.create(shield_type="全局屏蔽", shield_area="")


class Migration(migrations.Migration):
    dependencies = [
        ('ad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelShieldConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(default='', max_length=100, verbose_name='\u6e20\u9053\u5c4f\u853d')),
                ('start_time', models.DateTimeField(verbose_name='\u5f00\u59cb\u5c4f\u853d\u65f6\u95f4')),
                ('end_time', models.DateTimeField(verbose_name='\u7ed3\u675f\u5c4f\u853d\u65f6\u95f4')),
                ('first_created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('last_modify', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u6e20\u9053\u5c4f\u853d\u8bbe\u7f6e',
                'verbose_name_plural': '\u6e20\u9053\u5c4f\u853d\u8bbe\u7f6e',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_count', models.IntegerField(verbose_name='\u91d1\u5e01')),
                ('money', models.IntegerField(verbose_name='\u5bf9\u5e94\u4eba\u6c11\u5e01')),
                ('first_created', models.DateTimeField(auto_now_add=True, verbose_name='\u65e5\u671f')),
                ('last_modify', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u91d1\u5e01\u6c47\u7387\u8bbe\u7f6e',
                'verbose_name_plural': '\u91d1\u5e01\u6c47\u7387\u8bbe\u7f6e',
            },
        ),
        migrations.CreateModel(
            name='GlobalShieldConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shield_type', models.CharField(default='', max_length=100, verbose_name='\u5c4f\u853d\u7b56\u7565')),
                ('shield_area', models.TextField(default='', verbose_name='\u5c4f\u853d\u5730\u57df')),
                ('first_created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('last_modify', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u5168\u5c40\u5c4f\u853d\u8bbe\u7f6e',
                'verbose_name_plural': '\u5168\u5c40\u5c4f\u853d\u8bbe\u7f6e',
            },
        ),
        migrations.CreateModel(
            name='GoldConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_source', models.CharField(default='', max_length=200, verbose_name='\u5e7f\u544a\u6e90')),
                ('ad_type', models.CharField(default='', max_length=50, verbose_name='\u5e7f\u544a\u7c7b\u578b')),
                ('gold_count', models.IntegerField(default=0, verbose_name='\u91d1\u5e01')),
                ('first_created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('last_modify', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u91d1\u5e01\u8bbe\u7f6e',
                'verbose_name_plural': '\u91d1\u5e01\u8bbe\u7f6e',
            },
        ),
        migrations.CreateModel(
            name='RewardCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('\u9605\u8bfb\u65f6\u957f', 'read_last'), (
                    '\u4e0b\u8f7d\u5e94\u7528\u4f53\u9a8c\u65f6\u957f', 'experience_last')], max_length=50,
                                         verbose_name='\u7c7b\u578b')),
                ('last', models.IntegerField(default=10, verbose_name='\u65f6\u957f')),
                ('first_created', models.DateTimeField(auto_now_add=True, verbose_name='\u65e5\u671f')),
                ('last_modify', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u7ea2\u5305\u9886\u53d6\u6761\u4ef6\u8bbe\u7f6e',
                'verbose_name_plural': '\u7ea2\u5305\u9886\u53d6\u6761\u4ef6\u8bbe\u7f6e',
            },
        ),
        migrations.CreateModel(
            name='RewardCycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.IntegerField(default=0, verbose_name='\u5468\u671f')),
                ('first_created', models.DateTimeField(auto_now_add=True, verbose_name='\u65e5\u671f')),
                ('last_modify', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u7ea2\u5305\u5468\u671f\u8bbe\u7f6e',
                'verbose_name_plural': '\u7ea2\u5305\u5468\u671f\u8bbe\u7f6e',
            },
        ),
        migrations.CreateModel(
            name='RewardCycleCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='\u4e2a\u6570')),
                ('first_created', models.DateTimeField(auto_now_add=True, verbose_name='\u65e5\u671f')),
                ('last_modify', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u7ea2\u5305\u4e2a\u6570\u8bbe\u7f6e',
                'verbose_name_plural': '\u7ea2\u5305\u4e2a\u6570\u8bbe\u7f6e',
            },
        ),
        migrations.AlterModelOptions(
            name='adpolicy',
            options={'verbose_name': '\u5e7f\u544a\u7b56\u7565\u8bbe\u7f6e',
                     'verbose_name_plural': '\u5e7f\u544a\u7b56\u7565\u8bbe\u7f6e'},
        ),
        migrations.AddIndex(
            model_name='rewardcyclecount',
            index=models.Index(fields=['first_created'], name='ad_rewardcy_first_c_22093c_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardcycle',
            index=models.Index(fields=['first_created'], name='ad_rewardcy_first_c_dec0ab_idx'),
        ),
        migrations.AddIndex(
            model_name='goldconfig',
            index=models.Index(fields=['ad_source', 'ad_type'], name='ad_goldconf_ad_sour_a885e6_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['first_created'], name='ad_exchange_first_c_090be5_idx'),
        ),
        migrations.RunPython(forwards_func)
    ]
