# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0003_auto_20171124_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardcondition',
            name='last',
            field=models.IntegerField(default=10, verbose_name='\u65f6\u957f(\u79d2)'),
        ),
        migrations.AlterField(
            model_name='rewardcycle',
            name='cycle',
            field=models.IntegerField(default=0, verbose_name='\u5468\u671f(\u5206\u949f)'),
        ),
    ]
