# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0004_auto_20171202_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardcondition',
            name='typ',
            field=models.CharField(choices=[('read_last', 'H5'), ('experience_last', '\u4e0b\u8f7d')], max_length=50, verbose_name='\u7c7b\u578b'),
        ),
    ]
