# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_type', models.TextField(default='', verbose_name='\u63d0\u73b0\u91d1\u989d')),
                ('edit_by', models.CharField(default='', max_length=100, verbose_name='\u64cd\u4f5c\u4eba')),
                ('first_created', models.DateTimeField(auto_now_add=True, verbose_name='\u65e5\u671f')),
                ('last_modify', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u63d0\u73b0\u91d1\u989d\u8bbe\u7f6e',
                'verbose_name_plural': '\u63d0\u73b0\u91d1\u989d\u8bbe\u7f6e',
            },
        ),
        migrations.CreateModel(
            name='CashChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u63d0\u73b0\u6e20\u9053\u540d\u5b57')),
                ('first_created', models.DateTimeField(auto_now_add=True, verbose_name='\u65e5\u671f')),
                ('last_modify', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u63d0\u73b0\u6e20\u9053\u7c7b\u8bbe\u522b\u7f6e',
                'verbose_name_plural': '\u63d0\u73b0\u6e20\u9053\u7c7b\u8bbe\u522b\u7f6e',
            },
        ),
        migrations.AddField(
            model_name='cashcategory',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cash.CashChannel'),
        ),
    ]
