# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 06:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30, verbose_name='\u63d0\u73b0\u4eba\u586b\u5199\u7684\u624b\u673a\u53f7')),
                ('device_id', models.CharField(default='', max_length=200, verbose_name='device_id')),
                ('real_name', models.CharField(max_length=50, verbose_name='\u59d3\u540d')),
                ('identity', models.CharField(max_length=100, verbose_name='\u8eab\u4efd\u8bc1\u53f7')),
                ('machine_type', models.CharField(max_length=100, verbose_name='\u673a\u578b')),
                ('cash_type', models.CharField(default=100, max_length=100, verbose_name='\u5fae\u4fe1\u53f7/\u652f\u4ed8\u5b9d')),
                ('money', models.IntegerField(default=0, verbose_name='\u63d0\u73b0\u91d1\u989d(\u5206)')),
                ('status', models.CharField(choices=[('\u5f85\u5ba1\u6838', '\u5f85\u5ba1\u6838'), ('\u5df2\u901a\u8fc7', '\u5df2\u901a\u8fc7'), ('\u5df2\u62d2\u7edd', '\u5df2\u62d2\u7edd')], max_length=30, verbose_name='\u72b6\u6001')),
                ('reason', models.CharField(default='', max_length=200, verbose_name='\u539f\u56e0')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='\u63d0\u73b0\u4eba\u624b\u673a\u53f7')),
            ],
            options={
                'verbose_name': '\u63d0\u73b0\u8bb0\u5f55',
                'verbose_name_plural': '\u63d0\u73b0\u8bb0\u5f55',
            },
        ),
        migrations.AlterField(
            model_name='cashcategory',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cash.CashChannel', verbose_name='\u63d0\u73b0\u65b9\u5f0f'),
        ),
        migrations.AlterField(
            model_name='cashcategory',
            name='money_type',
            field=models.TextField(default='', verbose_name='\u63d0\u73b0\u91d1\u989d(\u5206)'),
        ),
    ]
