# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0002_auto_20171125_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashrecord',
            name='cash_type',
            field=models.CharField(default='', max_length=100, verbose_name='\u5fae\u4fe1\u53f7/\u652f\u4ed8\u5b9d'),
        ),
        migrations.AlterField(
            model_name='cashrecord',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='\u539f\u56e0'),
        ),
    ]
