# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 13:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0003_auto_20171125_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashrecord',
            name='channel',
            field=models.CharField(default='', max_length=50, verbose_name='\u6e20\u9053'),
        ),
        migrations.AddField(
            model_name='cashrecord',
            name='device_brand',
            field=models.CharField(default='', max_length=50, verbose_name='\u624b\u673a\u54c1\u724c'),
        ),
        migrations.AddField(
            model_name='cashrecord',
            name='first_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='\u65e5\u671f'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashrecord',
            name='last_modify',
            field=models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='cashrecord',
            name='version_num',
            field=models.CharField(default='', max_length=50, verbose_name='\u7248\u672c'),
        ),
        migrations.AlterField(
            model_name='cashrecord',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='\u7528\u6237\u586b\u5199\u7684\u624b\u673a\u53f7'),
        ),
        migrations.AlterField(
            model_name='cashrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='\u7528\u6237\u624b\u673a\u53f7'),
        ),
    ]
