# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0004_auto_20171125_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashMoneyCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold', models.IntegerField(default=0, verbose_name='\u91d1\u989d')),
                ('first_created', models.DateTimeField(auto_now_add=True, verbose_name='\u65e5\u671f')),
                ('last_modify', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
        ),
        migrations.AlterModelOptions(
            name='cashrecord',
            options={'verbose_name': '\u63d0\u73b0\u5ba1\u6838\u540e\u53f0  ', 'verbose_name_plural': '\u63d0\u73b0\u5ba1\u6838\u540e\u53f0'},
        ),
        migrations.RemoveField(
            model_name='cashcategory',
            name='money_type',
        ),
        migrations.AddField(
            model_name='cashcategory',
            name='money_type',
            field=models.ManyToManyField(to='cash.CashMoneyCategory', verbose_name='\u63d0\u73b0\u91d1\u989d(\u5206)'),
        ),
    ]
