# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 11:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statistics',
            options={'verbose_name': '\u5546\u4e1a\u6570\u636e\u7cfb\u7edf', 'verbose_name_plural': '\u5546\u4e1a\u6570\u636e\u7cfb\u7edf'},
        ),
        migrations.AddField(
            model_name='statistics',
            name='ad_source',
            field=models.CharField(default='', max_length=100, verbose_name='\u5e7f\u544a\u6e90'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='ad_type',
            field=models.CharField(default='', max_length=40, verbose_name='\u5e7f\u544a\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='channel',
            field=models.CharField(default='', max_length=100, verbose_name='\u6e20\u9053'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='click_count',
            field=models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u6570'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 12, 2, 11, 59, 13, 612735, tzinfo=utc), verbose_name='\u65e5\u671f'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='download_count',
            field=models.IntegerField(default=0, verbose_name='\u4e0b\u8f7d\u6570'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='first_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='\u65b0\u5efa\u65f6\u95f4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='gold_count',
            field=models.IntegerField(default=0, verbose_name='\u91d1\u5e01\u6570'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='install_count',
            field=models.IntegerField(default=0, verbose_name='\u5b89\u88c5\u6570'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='last_modify',
            field=models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='launch_count',
            field=models.IntegerField(default=0, verbose_name='\u6253\u5f00\u6570'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='show_count',
            field=models.IntegerField(default=0, verbose_name='\u5c55\u73b0\u6570'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='success_download_count',
            field=models.IntegerField(default=0, verbose_name='\u4e0b\u8f7d\u6210\u529f\u6570'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='success_install_count',
            field=models.IntegerField(default=0, verbose_name='\u5b89\u88c5\u6210\u529f\u6570'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='version',
            field=models.CharField(default='', max_length=40, verbose_name='\u7248\u672c'),
        ),
        migrations.AddIndex(
            model_name='statistics',
            index=models.Index(fields=['date', 'channel', 'version', 'ad_source', 'ad_type'], name='statistics__date_053dcd_idx'),
        ),
    ]
