# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0002_auto_20171202_1959'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='statistics',
            name='statistics__date_053dcd_idx',
        ),
        migrations.AlterField(
            model_name='statistics',
            name='date',
            field=models.DateField(verbose_name='\u65e5\u671f'),
        ),
        migrations.AlterUniqueTogether(
            name='statistics',
            unique_together=set([('date', 'channel', 'version', 'ad_source', 'ad_type')]),
        ),
    ]
