# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0003_auto_20171202_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='TStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='\u65e5\u671f')),
                ('ad_source', models.CharField(default='', max_length=100, verbose_name='\u5e7f\u544a\u6e90')),
                ('ad_position', models.CharField(default='', max_length=100, verbose_name='\u5e7f\u544a\u4f4d')),
                ('request_time', models.IntegerField(default=0, verbose_name='\u8bf7\u6c42\u6b21\u6570')),
                ('request_count', models.IntegerField(default=0, verbose_name='\u8bf7\u6c42\u6761\u6570')),
                ('return_count', models.IntegerField(default=0, verbose_name='\u8fd4\u56de\u5e7f\u544a\u6570')),
                ('show_count', models.IntegerField(default=0, verbose_name='\u5c55\u73b0\u6570')),
            ],
            options={
                'verbose_name': '\u5546\u4e1a\u6570\u636e\u7cfb\u7edf2',
                'verbose_name_plural': '\u5546\u4e1a\u6570\u636e\u7cfb\u7edf2',
            },
        ),
        migrations.AlterModelOptions(
            name='statistics',
            options={'verbose_name': '\u5546\u4e1a\u6570\u636e\u7cfb\u7edf1', 'verbose_name_plural': '\u5546\u4e1a\u6570\u636e\u7cfb\u7edf1'},
        ),
        migrations.AlterUniqueTogether(
            name='tstatistics',
            unique_together=set([('date', 'ad_source', 'ad_position')]),
        ),
    ]
