# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 07:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_by', models.CharField(default='', max_length=100, verbose_name='\u64cd\u4f5c\u4eba')),
                ('first_created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('last_modify', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u7248\u672c\u5347\u7ea7\u63a7\u5236',
                'verbose_name_plural': '\u7248\u672c\u5347\u7ea7\u63a7\u5236',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_num', models.CharField(default='', max_length=100, unique=True, verbose_name='\u7248\u672c\u53f7')),
                ('first_created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('last_modify', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u7248\u672c\u914d\u7f6e',
                'verbose_name_plural': '\u7248\u672c\u914d\u7f6e',
            },
        ),
        migrations.AddField(
            model_name='updateconfig',
            name='from_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_config_by_from_version', to='version.Version', verbose_name='\u9488\u5bf9\u7248\u672c'),
        ),
        migrations.AddField(
            model_name='updateconfig',
            name='to_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_config_by_to_version', to='version.Version', verbose_name='\u5347\u7ea7\u7248\u672c'),
        ),
    ]
