# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='updateconfig',
            name='akp_size',
            field=models.CharField(default='', max_length=50, verbose_name='apk\u5927\u5c0f'),
        ),
        migrations.AddField(
            model_name='updateconfig',
            name='is_force',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u5f3a\u5236'),
        ),
        migrations.AddField(
            model_name='updateconfig',
            name='md5',
            field=models.CharField(default='', max_length=100, verbose_name='md5'),
        ),
        migrations.AddField(
            model_name='updateconfig',
            name='release_note',
            field=models.TextField(default='', verbose_name='\u66f4\u65b0\u65e5\u5fd7'),
        ),
        migrations.AddField(
            model_name='updateconfig',
            name='url',
            field=models.URLField(default='', verbose_name='url'),
        ),
        migrations.AddField(
            model_name='version',
            name='version_name',
            field=models.CharField(default='', max_length=100, verbose_name='\u7248\u672c\u540d\u79f0'),
        ),
    ]
