# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0002_auto_20171210_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updateconfig',
            old_name='akp_size',
            new_name='apk_size',
        ),
    ]
